### ISSUE TITLE
Code runner not able to run python file because it can't find it

### ISSUE THREAD

**Issue by qbnil** [CRAG666/code_runner.nvim#108]
This was wierd because i could run the file manually by going to the directory and running python <file-name>, i have a hotkey for code-runner to run python files and that was the first time i had this issue: 
![image](https://github.com/CRAG666/code_runner.nvim/assets/130576530/80383a4d-66a1-4fd6-a2ea-85cd88c18a83)
![image](https://github.com/CRAG666/code_runner.nvim/assets/130576530/8a9b19b7-252c-4cdc-a9d9-94ff66d94862)
You see, it's right there, hope this is fixable

**Comment by CRAG666** [comment]
Pleace use python = "python -u '$dir/$fileName'" in your config
