### ISSUE TITLE
`:RunClose` only works from runner window

### ISSUE THREAD

**Issue by Rizhiy** [CRAG666/code_runner.nvim#119]
As title. It would be great to have a command which would close all runner windows from anywhere.
I want to add it as autocommand to automatically close runner window on close, because I use persistent sessions.
Also, I don't really want to switch to runner window every time to close it.
Maybe something like `:RunCloseAll`.

BTW, why do you unlist the code runner buffer? It makes it quite difficult to implement normal functionality using normal lua. This should definitely be an option. If it was listed, I could just do `:bd crunner*<CR>`.

**Comment by CRAG666** [comment]
Please send PR

**Comment by CRAG666** [comment]
@Rizhiy with BetterTerm mode this problem not exist
