### ISSUE TITLE
Not support in neovim 0.6.0 and 0.5.1

### ISSUE THREAD

**Issue by iChard** [CRAG666/code_runner.nvim#14]
![image](https://user-images.githubusercontent.com/12317840/146674893-aa8f2a1d-2fad-4dfb-92b6-eae465878215.png)

**Comment by JonathanxD** [comment]
My current workaround is to set the globals on my own (if you are not using `json`):

```lua
vim.g.fileCommands = {
    rust = 'cargo run'
}
```

**Comment by CRAG666** [comment]
Sorry for answering so far, work and the pandemic are overwhelming. From what I understand the error is when you configure with json or when you do it with lua?

**Comment by CRAG666** [comment]
I would like more information to replicate the error. Could you pass me your configuration?

**Comment by CRAG666** [comment]
The solution was simpler than it seemed, it was just removing a function that wasn't really doing anything, after that everything works as expected. Please, if you would be so kind as to verify if the problem was resolved, if so, please close the issue. Greetings

**Comment by CRAG666** [comment]
you can configure in pure lua without using json because from what I see is where the problem was. But now everything works fine

**Comment by CRAG666** [comment]
I will close this problem because it is similar to another one that is open
