### ISSUE TITLE
wrong in the output

### ISSUE THREAD

**Issue by jiadsii** [CRAG666/code_runner.nvim#16]
<img width="1280" alt="截屏2022-02-02 下午11 52 53" src="https://user-images.githubusercontent.com/45071541/152188795-44dfc5dd-1919-49d7-bb89-0c15d35513cf.png">

we can see the output and the code is not right in a line,
we donot know why it is narrow in the output line.

**Comment by CRAG666** [comment]
the plugin uses neovim's native terminal so this seems to be a terminal issue not the plugin

**Comment by jiadsii** [comment]
ok, how can I do for the terminal so that it can work well

**Comment by CRAG666** [comment]
pleace check http://vimdoc.sourceforge.net/htmldoc/term.html

**Comment by Pandademic** [comment]
@jiadsii It's not the terminal or the plugin , I think. Try fullscreening the terminal and trying. I don't think the width of the `split` is big enough

**Comment by Pandademic** [comment]
@CRAG666 what do you think?
