### ISSUE TITLE
Presumable bug with code segments prompting for user input and multiple terminals 

### ISSUE THREAD

**Issue by z0xyz** [CRAG666/code_runner.nvim#17]
Hello, i'm currently facing two "issues"
Firstly I have to press `i` every single time a piece of the code prompt the user for input . Like for instance if i have a python code with `input` function and run the whole file, then the terminal opens up but not place the cursor for input right away .
Secondly every single time i run , a new terminal windows pops up , so i constantly have to close them to have just one . Can't it be just one terminal window with the option to clear the previous output or even leave the previous output , but all within one single terminal window ?

**Comment by CRAG666** [comment]
First of all. None of the things you mention are problems. For the first point do this if you want any command to start in  insert mode.
example:
  "python3 % && :startinsert"

The second point occurs because the commands are oriented to terminals, that is to say that for each execution a new terminal is created, it would be interesting to use a single terminal for everything, it is probably a useful feature I will try to implement it over the weekend

**Comment by z0xyz** [comment]
> First of all. None of the things you mention are problems. For the first point do this if you want any command to start in insert mode.
> example:
> "python3 % && :startinsert"

I've tried to substitute my `filetype` of the `python` property value with this  `"python3 % && :startinsert"`, i still had to press either `i` or `a` and additionally got prompted with this error `/bin/bash: :startinsert: command not found`
Can i get to know where this rightfully place this command ?

**Comment by CRAG666** [comment]
"python": "python -u $fileName | :startinsert"

**Comment by CRAG666** [comment]
you can add the `mode = "start insert"` option to setup. That will make the terminal when you run a command start in mod insert
https://github.com/CRAG666/code_runner.nvim/commit/1c9bd9e415bf202cf66831b41771d70b65a94a99

**Comment by CRAG666** [comment]
@z0xyz pleace check README

**Comment by z0xyz** [comment]
> you can add the `mode = "startinsert"` option to setup.
Thanks ! Insert mode works just fine right now !

**Comment by CRAG666** [comment]
yes I understand, but there are already many plugins with those characteristics to include this is to use some repl service which is really not very useful considering that it is normally used for debugging and well for debugging it is already dap and it is very good at this, but how I tell you I am open to live prs

**Comment by CRAG666** [comment]
By the way I already solved the problem so I opened the issue so you could check if it is what you wanted and secondly if it is yes close this issue and open some others with features that could be useful. Remember that code runner aims to be as simple as possible without losing its usefulness. Greetings

**Comment by z0xyz** [comment]
> code runner aims to be as simple as possible without losing its usefulness.
Noted .
Thanks for the time considering it .
