### ISSUE TITLE
PDM Pep582 Support

### ISSUE THREAD

**Issue by KarimLeVallois** [CRAG666/code_runner.nvim#20]
I'm running Python scripts using "Python3", but need to run eval "$(pdm --pep582)" before I can run any code to set the environment variable. I've tried multiple "cmd" and "shell_cmd" options but cannot get it to work with my macOS Zsh setup. The auto setting of the variable is in my .zprofile and works when running the script through the integrated terminal or my external terminal iTerm2, just not code_runner. Any ideas on how to get this to work?

https://pdm.fming.dev/

**Comment by CRAG666** [comment]
It's hard for me to test this since I don't have a mac. I'll try to fix it. You can too, the code shouldn't be hard to understand, basically you just need to modify the prefix to one that works for you. Can you help me by providing the complete command to run a script in python

**Comment by KarimLeVallois** [comment]
I did something REALLY silly! I have a separate .zshrc that I use for Neovim, but I hadn't added the variable to it. Everything works now, sorry to waste your time.
