### ISSUE TITLE
error: attempt to index field 'term' (a nil value)

### ISSUE THREAD

**Issue by xarthurx** [CRAG666/code_runner.nvim#21]
![image](https://user-images.githubusercontent.com/1921878/161095738-93250caf-7545-4a1a-8ef1-baf73e6f3fd6.png)

when executing `:lua require('code_runner').setup({})`
neovim: `0.6.1`
OS: windows

**Comment by xarthurx** [comment]
If put it in the setting files, `PackerSync` gives:

![image](https://user-images.githubusercontent.com/1921878/161096373-91233584-0a43-4c0d-9e36-c63ae0f23899.png)

**Comment by CRAG666** [comment]
brange?

**Comment by xarthurx** [comment]
What do you mean by `brange`?

**Comment by CRAG666** [comment]
Sorry I was referring to the branch, but forget it, use setup with values, in the master branch it doesn't work without values, in fact this branch will no longer be modified in favor of the nvim-7 branch because many of the current problems were corrected there.

**Comment by xarthurx** [comment]
OK, thanks for the reply.
I'll then probably wait for a few weeks until the nvim-7 relesases.

**Comment by xarthurx** [comment]
Hello, since `neovim-v0.7` has been released, which branch is the most recent now?

**Comment by CRAG666** [comment]
nvim-7 is here :)

**Comment by CRAG666** [comment]
@xarthurx This error no longer exists because embedded vimscript will no longer be used to create commands.
