### ISSUE TITLE
Doesn't work when file is in directory with more than one word

### ISSUE THREAD

**Issue by pavanscoding** [CRAG666/code_runner.nvim#31]
I had a python program in a directory called "Competitive  Programming". The plugin failed as I didn't have a directory called Competitive. 
![image](https://user-images.githubusercontent.com/75864715/181768997-ebfabf9c-e991-4189-8d2a-b1a3b3747d5b.png)

**Comment by CRAG666** [comment]
You could show your setup please

**Comment by Sam-Hobson** [comment]
I've just made a PR that should fix this

**Comment by CRAG666** [comment]
@Sam-Hobson Thanks for your PR, but for the next PR please you have reference to the ISSUE, you can do it with an commitment that takes the ISSUE number.
