### ISSUE TITLE
Error when executing

### ISSUE THREAD

**Issue by ElcomJ** [CRAG666/code_runner.nvim#36]
Good evening, I have always used this plugin to be able to run my python codes, and I have to congratulate the creator because his plugin is just perfect.

Earlier today I could run my code normally through your plugin, but I tried to run it again and it is showing this error in the `image below`:

![Captura de tela de 2022-08-04 17-57-10](https://user-images.githubusercontent.com/37147897/182951259-b0f75904-cb5f-4f72-aa70-e46b6640cd88.png)

Picture of `my configuration`:

![Captura de tela de 2022-08-04 17-59-45](https://user-images.githubusercontent.com/37147897/182951671-0c810096-581c-467a-8119-6a022db4b60b.png)

Is there a solution to this error?

**Comment by carlisia** [comment]
Same here, I too started getting the "No such file or directory". error.

**Comment by Sam-Hobson** [comment]
Opps! I made a really dumb mistake when fixing issue #31 . I'll fix that now.

**Comment by ElcomJ** [comment]
Good morning, has the error been fixed yet?

Because I ran a `PlugUpdate` to update my `Plugins` and tried to run my file and again showed the same output.

**Comment by CRAG666** [comment]
@ElcomJ If you have the same error, it is very likely that your command sequence is incorrect, for example, execute a .py file "python3 -u" no "python3"

**Comment by ElcomJ** [comment]
Good afternoon @CRAG666 , the error was fixed in commit  `8fc0a2d` , it is already working normally.

Thanks for your attention and great work :)
