### ISSUE TITLE
can I use this for my game engine

### ISSUE THREAD

**Issue by GingerNinjaStickdudeWorld** [CRAG666/code_runner.nvim#38]
I'm making a game engine with both block/visual code and written code, I have the block stuff mostly sorted and I want to see if I can use this for the written code because lua is the easiest programming language I know.

**Comment by GingerNinjaStickdudeWorld** [comment]
> 

the name of the game engines repository is called creative world

**Comment by CRAG666** [comment]
Please more info

**Comment by GingerNinjaStickdudeWorld** [comment]
> Please more info

nvm I scrapped the project
