### ISSUE TITLE
How to use <C-c> to exit infinity loop?

### ISSUE THREAD

**Issue by NEX-S** [CRAG666/code_runner.nvim#39]
How to use `<C-c>` to exit the infinity loop?

**Comment by CRAG666** [comment]
please send the video

**Comment by NEX-S** [comment]
Solved with `vim.keymap.set('n', '<C-c>', '', { noremap = true, silent = true }`, nvim is mapping `<C-c>` as quit, so sometimes `<C-c>` is not working in code_runner floating windows.

**Comment by CRAG666** [comment]
Pleace close issue
