### ISSUE TITLE
Python focus

### ISSUE THREAD

**Issue by KarimLeVallois** [CRAG666/code_runner.nvim#4]
How would I go about setting up the .json file to run in python3, but to start on insert so I can use the terminal interactively? Also, the -U doesn't seem to work in python3

**Comment by KarimLeVallois** [comment]
Thanks for coming back so quickly. So is there no way to have the terminal open in insert mode? I currently have a keybinding set up which does this "<cmd>:vsplit term://python3 % | :startinsert<CR>”

**Comment by CRAG666** [comment]
It could be done by adding a variable named suffix, actually I had it before but I got feedback that it was a better idea to remove it and start in normal mode. But you could venture and add it to the new_features branch, anyway I always check the PR and accept any ideas :)

**Comment by KarimLeVallois** [comment]
Sorry, but new at all this. Could you please tell me how to do that workaround?

**Comment by CRAG666** [comment]
If you don't want to complicate things, just add this to your json file: 
"python": "python -u $fileName | :startinsert"

Don't forget to remove the above python command

**Comment by KarimLeVallois** [comment]
"python": "python3 % && <cmd>:startinsert<CR>" worked!

**Comment by KarimLeVallois** [comment]
Last question before I close this... What is the command to run the actual code? I'd rather add a keybinding to whichkey, rather than in the config file itself.

**Comment by KarimLeVallois** [comment]
Or just be able to rename the mapping so in whichkey it just says 'Code Runner', rather than belowright 8split term://...

**Comment by CRAG666** [comment]
Check the branch of new_features, there is what you want, next week I will merge the branches, but you can check before the merge, in the readme file of the main branch it is how to install from the branch of new_features. Don't forget to promote the plugin, to make it the best of its kind

**Comment by KarimLeVallois** [comment]
Awesome, works perfectly, will spread the word! :)
