### ISSUE TITLE
attempt to call a nil value

### ISSUE THREAD

**Issue by yangxing844** [CRAG666/code_runner.nvim#40]
**while trying to run project I got this error, runing a single file is fine.**
`Error executing Lua callback: ...e/pack/packer/start/code_runner.nvim/lua/code_runner.lua:75: attempt to call a nil va
lue
stack traceback:
        ...e/pack/packer/start/code_runner.nvim/lua/code_runner.lua:75: in function <...e/pack/packer/start/code_runne
r.nvim/lua/code_runner.lua:75>`
**below is my setup for code_runner, 
I am using neovim-nightly and the plugin are updated to the latest. this happened recently**
`	use({
		"CRAG666/code_runner.nvim",
		requires = "nvim-lua/plenary.nvim",
		config = function()
			require("code_runner").setup({
				term = { position = "vert", size = 15 },
				mode = "toggleterm",
				filetype = {
					java = "cd $dir && javac $fileName && java $fileNameWithoutExt",
					python = "python ",
					lua = "lua ",
					rust = "cd $dir && mkdir -p .bin && rustc -g $fileName -o .bin/$fileNameWithoutExt && .bin/$fileNameWithoutExt",
					cpp = "cd $dir && mkdir -p .bin && g++ -g $fileName -o .bin/$fileNameWithoutExt && .bin/$fileNameWithoutExt",
					c = "cd $dir && mkdir -p .bin && gcc -g $fileName -o .bin/$fileNameWithoutExt && .bin/$fileNameWithoutExt",
				},
				project = {
					["~/playground/c++/open-gl"] = {
						name = "open gl learning",
						description = "repo to learn open gl",
						file_name = "main.cpp",
						command = "make -C build run",
					},
					["~/playground/c++/dict_cpp"] = {
						name = "My Dictionary app",
						description = "compile dict",
						command = "make run",
					},
				},
			})
		end,
	})
`

**Comment by CRAG666** [comment]
What filetype do I try to execute?

**Comment by yangxing844** [comment]
thanks you very much, it iis fixed!
