### ISSUE TITLE
Error 471

### ISSUE THREAD

**Issue by ElcomJ** [CRAG666/code_runner.nvim#42]
Good morning, after the last commit the plugin stopped working in my neovim, when I try to run it, it returns an E471 as shown in the image below:

![image](https://user-images.githubusercontent.com/37147897/187979108-94fc757c-18ae-4d8d-9712-46efa5098ade.png)

I wonder if there is any way to solve it?

**Comment by fennelcakes** [comment]
Before the rollback I had it working by changing the command to `:RunCode &ft`, just for reference
