### ISSUE TITLE
`:RunClose` 'crashes' nvim

### ISSUE THREAD

**Issue by tardiobscurus** [CRAG666/code_runner.nvim#51]
```
nvim: v0.7.2
```

When I run `:RunClose` the nvim will freeze and won't be back to normal, forcing me to close the editor having unsaved files.
Don't know the reason, but I've updated nvim and the plugin itself, yet to fix the problem.

To do the problem described;
Just like any file, do `:RunCode`, then do `:RunClose` which freezes the editor and no way to revert back.

**Comment by sheeperino** [comment]
Same here
```nvim: v0.8.1```

**Comment by CRAG666** [comment]
Please screenshot

**Comment by azinsharaf** [comment]
hi @CRAG666 
first let me thank you. I'm excited to use it since it would save my coding time.

`:RunClose` freezes neovim. 

NeoVim version : 0.8.3


https://user-images.githubusercontent.com/10101468/222235091-21fdab2b-872e-490f-ad44-be40b10aeb79.mp4

**Comment by azinsharaf** [comment]
I edited my configuration and now `:RunClose` doesn't freeze neovim. Hope it stays stable. Just in case someone else has the same issue this is my configuration using lazy.nvim.
```
NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az171-224

Features: -acl +iconv +tui
See ":help feature-compile"
system vimrc file: "$VIM\sysinit.vim"
fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
coderunner.lua plugin configuration:
```
```
return {
  "CRAG666/code_runner.nvim",
  lazy = false,
  init = function() require("which-key").register({ ["<leader>r"] = { name = "Code Runner" } }, { mode = "n" }) end,
  opts = {
    filetype = {
      python = "C:/Users/<path>/python.exe"
    },
  },
  keys = {
    { "<leader>rr", "<cmd>RunCode<cr>",    desc = "Run Code" },
    { "<leader>rf", "<cmd>RunFile<cr>",    desc = "Run File" },
    -- { "<leader>rft", "<cmd>RunFile tab<cr>", desc = "Run File Tab" },
    { "<leader>rp", "<cmd>RunProject<cr>", desc = "Run Project" },
    { "<leader>rc", "<cmd>RunClose<cr>",   desc = "Run Close" },
    -- { "<leader>crf", "<cmd>CRFiletype<cr>", desc = "Open Json supported files" },
    -- { "<leader>crp", "<cmd>CRProject<cr>", desc = "Open Json list of projects" },
  },
}
```
