### ISSUE TITLE
Is executing a range from the current buffer possibe?

### ISSUE THREAD

**Issue by pranavpa8788** [CRAG666/code_runner.nvim#52]
First of all, very useful plugin and has been satisfying so far to use. Just wondering is there a feature where I can execute a specified range (as in selected using visual mode), similar to snip run. 

Tried RunCode on a range but it said no ranges allowed

**Comment by CRAG666** [comment]
It is not something that I use often, so I do not implement it (I do not plan to do it, because I do not use it).But if you have enough time I could send a PR and I gladly accept it.

**Comment by pranavpa8788** [comment]
Thanks for the clarification man. I'll try to work on it someday whenever I have the time. Great plugin man, works smooth as butter so far!
