### ISSUE TITLE
How to pass command line arguments to the script?

### ISSUE THREAD

**Issue by skamsie** [CRAG666/code_runner.nvim#53]
Is there a way to pass command line arguments when running with `RunCode` or `RunFile`?

**Comment by sigmaSd** [comment]
I added support to passing argument to RunCode, you can see an example of how I'm using it here https://github.com/CRAG666/code_runner.nvim/pull/43

**Comment by CRAG666** [comment]
@sigmaSd  thanks place read. @skamsie The ISSUE closes if your problem is solved
