### ISSUE TITLE
Run a specific piece of code

### ISSUE THREAD

**Issue by ElcomJ** [CRAG666/code_runner.nvim#56]
Good afternoon, how are you?

I would like to know if it is possible to `execute a specific piece of code` instead of executing the whole code.

Currently I use the `:RunFile` command, but I would like to be able to select a piece of code in `VISUAL MODE` and run it.

Is it possible to do this?

Congratulations on your plugin, it is just perfect :)

**Comment by CRAG666** [comment]
Thank you for the beautiful words, it is not in my plans to implement this, since I do not use this function, but maybe you can venture and do this RPL with pleasure I accept your PR.As I told you, I don't usually use this characteristic perhaps in the future, try to implement it

**Comment by ElcomJ** [comment]
Good afternoon @CRAG666 , thanks for the reply.
Unfortunately at the moment I don't have much affinity with the `Lua language`, so much that my init.vim is all in vimscript 😅.

But thanks anyway, thanks again for your great plugin and have a great day :)

OBS: If someone see this Issue having the same problem, what I did to be able to run it was install the `ipython` and open a side terminal with it open, so I could copy the piece of code I want to test and paste it in :)
