### ISSUE TITLE
How to keep terminal running after execution?

### ISSUE THREAD

**Issue by MustafaLinux** [CRAG666/code_runner.nvim#57]
Hi, I want the terminal to keep running after the execution is finished.
And it will be nicer to make the plugin doesn't close the old tab and create new terminal every time it runs, rather just past the file type command with absolute path and run it, and keep the terminal open which let me see the previous output and compare with the old one.

In short, I want to make it function like the one in vscode.

**Comment by CRAG666** [comment]
Of course you can achieve this, simply use my other plugin for the handling of the terminal
https://github.com/CRAG666/betterTerm.nvim
```lua
  vim.keymap.set("n", "<leader>e", function()
    require("betterTerm").send(require("code_runner.commands").get_filetype_command(), 1, false)
  end, { desc = "Excute File" })
```
This is just what you need, assign the combination you like the most
The ISSUE closes if this was helpful if we cannot segir iterando
@MustafaLinux thanks

**Comment by MustafaLinux** [comment]
Thank you, I didn't know about that.
But although it keeps the terminal running, it's still refreshing every time I run it.
Any idea how I can prevent that?

**Comment by CRAG666** [comment]
If there will be a problem

**Comment by CRAG666** [comment]
@MustafaLinux A better terminal has already been implemented natively, so this is the solution to this problem
