### ISSUE TITLE
How to disable wrap output on terminal

### ISSUE THREAD

**Issue by madyardwn** [CRAG666/code_runner.nvim#64]

**Comment by CRAG666** [comment]
please screenshot or description

**Comment by madyardwn** [comment]
It was like this
![image](https://user-images.githubusercontent.com/88965430/212311715-c091bbbb-3dda-4922-8d0c-e0e5aedac69b.png)
My code_runner output is set to 'vert' in that example the text wraps down when it hits the terminal the max width vertically.

What I want is, can I make the code_runner console output unwrapped? instead we can swipe left and right to see them

**Comment by CRAG666** [comment]
You could add a function that is executed before a command is finished and in it you can add the options you want
