### ISSUE TITLE
Running code inside a folder that have spaces on its name results in "too many arguments" error (and how to fix it)

### ISSUE THREAD

**Issue by yosuanicolaus** [CRAG666/code_runner.nvim#67]
I'm using the default lazy configuration from the [README](https://github.com/CRAG666/code_runner.nvim#:~:text=filetype%20%3D%20%7B%0A%20%20%20%20javascript,fileNameWithoutExt%22%2C%0A%20%20%7D%2C)

![image](https://user-images.githubusercontent.com/87525599/219936583-ff3b55b4-d534-414a-87bb-db2c672b3d88.png)

Problem:
The RunCode/RunFile command works well, except for when we are trying to run file inside a directory that has space(s) in its name- for example: "Chapter 03 - If"/ folder.

![image](https://user-images.githubusercontent.com/87525599/219936828-5347d032-f84b-4b51-9497-0695319b0157.png)

If we rename the directory to not have spaces, it will work as expected

![image](https://user-images.githubusercontent.com/87525599/219936883-6501a804-0a5d-4436-9545-9604d5b30802.png)

I suspect it has something to do with how [the "$dir"](https://github.com/CRAG666/code_runner.nvim/blob/main/lua/code_runner/commands.lua#L26) in filetype from setup returns the string. I found a quick fix by wrapping the $dir with a ' ' (colon) will work as expected.

```lua
-- before
cpp = "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir/$fileNameWithoutExt",
```

```lua
-- after
cpp = "cd '$dir' && g++ $fileName -o $fileNameWithoutExt && '$dir/$fileNameWithoutExt'",
```

**Comment by CRAG666** [comment]
use this
-- after
cpp = "cd '$dir' && g++ $fileName -o $fileNameWithoutExt && '$dir/$fileNameWithoutExt'",

**Comment by Makima777** [comment]
> use this -- after cpp = "cd '$dir' && g++ $fileName -o $fileNameWithoutExt && '$dir/$fileNameWithoutExt'",

But on the Windows, this commad is not useful in powershell, how should I do?
the terminal is like
```bash
#"cd
>
```

**Comment by Hobbyist11** [comment]
Doesn't work if mode = "toggleterm" is set.
