### ISSUE TITLE
problen with the spaces in an file/folder name

### ISSUE THREAD

**Issue by alavaelian** [CRAG666/code_runner.nvim#68]
for example i have the file named program one
code runner will execute 
g++ program 
g++ one
givin an error becose none of these files exist
i tried to fix it with the other threath about this but only works for the directory

**Comment by CRAG666** [comment]
just use quotes and that's it

**Comment by alavaelian** [comment]
> just use quotes and that's it

not working hommie thanks for the answer

**Comment by alavaelian** [comment]
thanks for the answer
