### ISSUE TITLE
nevim freezes after `:RunClose`

### ISSUE THREAD

**Issue by azinsharaf** [CRAG666/code_runner.nvim#69]
hi @CRAG666
posting this here as a separate issue since the other one (#51) is closed. 
first let me thank you. I'm excited to use it since it would save my coding time.

:RunClose freezes neovim.

NeoVim version : 0.8.3

https://user-images.githubusercontent.com/10101468/222516847-cbe5032c-3678-4ad4-a4c0-098f1905eef1.mp4

**Comment by CRAG666** [comment]
Unfortunately I don't have windows to test that error. After reading this I tried in linux with your specific version and everything works fine so I concluded that maybe it is a matter of the operating system, I will wait for confirmation if someone else has problems with linux

**Comment by azinsharaf** [comment]
I edited my configuration and now `:RunClose` doesn't freeze neovim. Hope it stays stable. Just in case someone else has the same issue this is my configuration using lazy.nvim.
```
NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az171-224

Features: -acl +iconv +tui
See ":help feature-compile"
system vimrc file: "$VIM\sysinit.vim"
fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

`coderunner.lua` plugin configuration:

```
return {
  "CRAG666/code_runner.nvim",
  lazy = false,
  init = function() require("which-key").register({ ["<leader>r"] = { name = "Code Runner" } }, { mode = "n" }) end,
  opts = {
    filetype = {
      python = "C:/Users/<path>/python.exe"
    },
  },
  keys = {
    { "<leader>rr", "<cmd>RunCode<cr>",    desc = "Run Code" },
    { "<leader>rf", "<cmd>RunFile<cr>",    desc = "Run File" },
    -- { "<leader>rft", "<cmd>RunFile tab<cr>", desc = "Run File Tab" },
    { "<leader>rp", "<cmd>RunProject<cr>", desc = "Run Project" },
    { "<leader>rc", "<cmd>RunClose<cr>",   desc = "Run Close" },
    -- { "<leader>crf", "<cmd>CRFiletype<cr>", desc = "Open Json supported files" },
    -- { "<leader>crp", "<cmd>CRProject<cr>", desc = "Open Json list of projects" },
  },
}
```
