### ISSUE TITLE
Code_runners doesn't seem to work on lunarvim

### ISSUE THREAD

**Issue by Chloroxite** [CRAG666/code_runner.nvim#70]
Alright I'm gonna be honest, I'm a new lunarvim user, so I might be doing something wrong, but I attempted to install the plugin by adding it to the config.lua file under the "additional plugins" section of the config. While it did appear to install (the files are where they should be at least), I cannot seem to use any of the commands. Is this an issue with lunar vim? Am I missing something?

**Comment by dorrajmachai** [comment]
Hello,

Former LunarVim and Neovim from Scratch user, here. Could you provide a few more details? What does your config file look like? I have the plugin installed and am able to use it without any problems. [My configuration](https://github.com/dorrajmachai/nvim/blob/main/lua/plugins/code_runner.lua) is available in my ```nvim``` repo. I am using my own config now, with Lazy as a plugin manager. If you can add more information to your issue, I'm happy to try to help you troubleshoot!

**Comment by dorrajmachai** [comment]
Hello,

Is it possible for me to work on this issue? Basically, I'd like to provide links to the documentation provided by different neovim distributions (LunarVim, NvChad, nyoom, etc.). Additionally, and I ask this as someone that doesn't contribute to a lot of projects, would it be beneficial to add links to the user plugins files for each preconfigured distribution so prospective users (particularly people trying to get started with Neovim) don't have to spend a lot of time searching? I believe this would be a thorough solution that would allow you to close the issue. Please let me know!
