### ISSUE TITLE
e492

### ISSUE THREAD

**Issue by nevdawg123** [CRAG666/code_runner.nvim#71]
I'm currently using a version of kickstart.nvim and when i added the plugin and set the keymap every time i try to run a file or code it says "e492: not an editor command:Run File, or run code:
![Screenshot 2023-03-13 at 7 39 58 PM](https://user-images.githubusercontent.com/127357709/224862978-891c6ece-d53d-4fe0-8ba5-46dc412db28e.png)

**Comment by Skylli202** [comment]
Hi @nevdawg123,

I'm also starting my neovim journey with `kickstart.nvim` and I have issue installing `code_runner`.
How did you install it ? I think that the error is coming from a bad installation.

**Comment by dorrajmachai** [comment]
@nevdawg123,

Have you tried this? What does your config look like? I think more information would help make your issue clearer. Thanks!

**Comment by Uttah** [comment]
> @nevdawg123,
> 
> Have you tried this? What does your config look like? I think more information would help make your issue clearer. Like, @Skylli202, I've shared [my config](https://github.com/CRAG666/code_runner.nvim/issues/70#issuecomment-1477451421) to give an example of what works. Any updated information from you will be greatly appreciated. Thanks!

I caught the same after migrate to Lazy (with your config)...

**Comment by dorrajmachai** [comment]
@Uttah Can you share your config file, as well as your ```nvim``` and OS? It's hard to diagnose the issue without at least those things. Thanks!

**Comment by f-steinbauer** [comment]
Hi, can you verify if the plugin is loaded by `:Lazy`? If not the commands won't be available.
In case it's not loaded, try to add `event = "VeryLazy"` to your config and try again.
```lua
return {
  "CRAG666/code_runner.nvim",
  event = "VeryLazy",
  opts = {
      filetype = {
      ...
     },
}
```

**Comment by CRAG666** [comment]
@dorrajmachai use this in lazy config: 
```lua
  keys = {
    {
      "<leader>e",
      function()
        require("code_runner").run_code()
      end,
      desc = "[e]xcute code",
    },
  },

```

**Comment by SuperCowProducts** [comment]
Hi @CRAG666, thanks for the suggestion! Do you know what's going wrong here? I'm trying to isolate plugin installation and config in one file, `~/.config/nvim/plugins/lua/code_runner.lua`, but at the moment `RunCode` isn't available:

```lua
return {
  "CRAG666/code_runner.nvim",
  cmd = { "RunCode", "RunFile", "RunProject", "RunClose", "CRFiletype", "CRProjects" },
  keys = {
    {
      "<leader>e",
      function()
        require("code_runner").run_code()
      end,
      desc = "[e]xcute code",
    },
  },
  opts = {
    -- your config (mode, filetype, ...) goes here
  },
}
```
