### ISSUE TITLE
Stuck when using exteral storage

### ISSUE THREAD

**Issue by NateCC0902** [CRAG666/code_runner.nvim#72]
OS: MacOs 13.2.1
Neovim: 0.8.3
Exteral storage: Samsung T7

It works on my local storage. 
Oterh coderunner plugins able to run on exteral storage (spinrun).
Both file file format APFS and ExFAT have same issue.
All lagnuage have same situation (Java, python, typescript etc....)

The issue is:
when I type cmd `:RunCode`, the whole termainl freeze and cpu useage goes 99%. Need to reboot everything.

Config:
https://github.com/NateCC0902/nvim/blob/main/after/plugin/coderunner.lua

**Comment by CRAG666** [comment]
I don't quite understand what the problem could be, I guess it's the command, could you try all the commands you have configured?

**Comment by NateCC0902** [comment]
what do you mean? 
I tried command on terminal and its fine. and other nvim plugins are fine as well.
I asked Chatgpt that said it could be neovim i/o issue?

**Comment by NateCC0902** [comment]
I have tried different mode term float ... still stucking.

This file is log from macos. it might be helpful
[nvim的樣本.txt](https://github.com/CRAG666/code_runner.nvim/files/11058222/nvim.txt)

**Comment by CRAG666** [comment]
@NateCC0902  I already had this problem, I have already solved it, the problem occurred due to how the match with the projects worked, the new version no longer has this problem, you can verify

**Comment by NateCC0902** [comment]
Thx!
