### ISSUE TITLE
How can I toggle RunCode and RunClose with the same keymap?

### ISSUE THREAD

**Issue by AbdoOmarEg** [CRAG666/code_runner.nvim#79]
I use <leader>r to run the code, is it possible to RunClose with <leader>r too?

**Comment by CRAG666** [comment]
You can use vim.w to store a variable to determine whether or not it is running.

**Comment by CRAG666** [comment]
@AbdoOrigin Currently with better_term mode you can assign a key to toggle the terminal

**Comment by justicenyaga** [comment]
I know this is closed, but, I achieved the desired functionality by just using lua.

Here's a snippet on how to go about it for anyone who might want to implement this.

```lua
vim.keymap.set("n", "<leader>ex", function()
  local bufname = vim.fn.bufname("%")
  if bufname:find("crunner_") then
    vim.cmd("RunClose")
  else
    vim.cmd("RunCode")
  end
end, { desc = "Toggle Code Runner" })
```

**Comment by AbdoOmarEg** [comment]
> I know this is closed, but, I achieved the desired functionality by just using lua.
> 
> Here's a snippet on how to go about it for anyone who might want to implement this.
> 
> ```lua
> vim.keymap.set("n", "<leader>ex", function()
>   local bufname = vim.fn.bufname("%")
>   if bufname:find("crunner_") then
>     vim.cmd("RunClose")
>   else
>     vim.cmd("RunCode")
>   end
> end, { desc = "Toggle Code Runner" })
> ```

Yeah that's exactly what I wanted a while back
