### ISSUE TITLE
[FEATURE REQUEST] Ability to execute custom functions.

### ISSUE THREAD

**Issue by Borwe** [CRAG666/code_runner.nvim#8]
EG:
```
{
"cmake-build": "mkdir build && cd build && cmake ../ && $$findExecutableToExecute"
}
```

So when it reaches the ```$$finExecutableToExecute``` it will run a function that looks for an executable and returns the executable path.

**Comment by CRAG666** [comment]
When you add a project the project has the option to add a custom command,
Even using the variables that already exist, you could reach the result you expect, but maybe if you are more explicit with the new function, program it this weekend and add it to the new_features branch.

**Comment by Borwe** [comment]
How does the project thing work? I need to define a new project in json for every new one I create? It appears to me to be mapped directly to the directory.

**Comment by CRAG666** [comment]
It is related to a directory, but you could make a pr with what you want, I check it if it is a good idea I add it
