### ISSUE TITLE
a minor typo

### ISSUE THREAD

**Issue by azinsharaf** [CRAG666/code_runner.nvim#84]
![image](https://github.com/CRAG666/code_runner.nvim/assets/10101468/0657c90f-7608-449b-8462-e8a9a092ea37)

**Comment by saccarosium** [comment]
Thanks @azinsharaf, do you mind make a PR yourself? It is always a good first PR fixing typos!

**Comment by azinsharaf** [comment]
Yeah, i'd love to!
