### ISSUE TITLE
readme issues

### ISSUE THREAD

**Issue by rwijtvliet** [CRAG666/code_runner.nvim#97]
This link (`code_runner.lua`) is dead:

<img width="730" alt="image" src="https://github.com/CRAG666/code_runner.nvim/assets/4106013/42b28866-e0a5-40f9-a8b9-e83f1e53b84b">

And if I understand this correctly, `mode` is not type bool but string:

<img width="987" alt="image" src="https://github.com/CRAG666/code_runner.nvim/assets/4106013/6be982e3-d5b0-4bdc-98ee-3025b3e4148e">

**Comment by CRAG666** [comment]
Pleace send PR
